site_name: RoboWeldAR ROSE-AP
repo_url: https://github.com/ikh-innovation/roboweldar-rose-ap.git
site_description: RoboWeldAR ROSE-AP Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - 'Home': '../README.md'
  - 'User & Programmers Manual':
    - 'Architecture' : 'architecture.md'
    - 'API' : 'api.md'
    - 'User Guide': 'usermanual.md'
    - 'Test Examples': '../test/README.md'
  - 'Installation & Administration Manual': 
    - 'Installation Guide': 'docs/installationguide.md'
    - 'Docker Guide': '../docker/README.md'
